"""add twilio_call_sid to calls

Revision ID: 2e8bf80022ad
Revises: 40a80aeb061e
Create Date: 2026-05-19 17:21:51.299084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8bf80022ad'
down_revision: Union[str, Sequence[str], None] = '40a80aeb061e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('twilio_call_sid', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'calls', ['twilio_call_sid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calls', type_='unique')
    op.drop_column('calls', 'twilio_call_sid')
    # ### end Alembic commands ###
